LIB_DIR = ../lib
INCLUDE = -I../include -I./utils
CFLAGS = -O0 -g3 -static
CFLAGS += -march=rv64gcvxthead -mabi=lp64dv
CFLAGS += -ffunction-sections -fdata-sections -Wl,--gc-sections
CFLAGS += -DCSINN_API=3
LIB_NAME = csi_nn2_c906
CC = riscv64-unknown-linux-gnu-gcc

test_objs =

test_objs += validation/sin_f32.o
test_objs += validation/sin_u8.o
test_objs += validation/sinh_f32.o
test_objs += validation/sinh_u8.o
test_objs += validation/asin_f32.o
test_objs += validation/asin_u8.o
test_objs += validation/asinh_f32.o
test_objs += validation/asinh_u8.o
test_objs += validation/cos_f32.o
test_objs += validation/cos_u8.o
test_objs += validation/cosh_f32.o
test_objs += validation/cosh_u8.o
test_objs += validation/acos_f32.o
test_objs += validation/acos_u8.o
test_objs += validation/acosh_f32.o
test_objs += validation/acosh_u8.o
test_objs += validation/tan_f32.o
test_objs += validation/tan_u8.o
test_objs += validation/tanh_f32.o
test_objs += validation/tanh_u8.o
test_objs += validation/atan_f32.o
test_objs += validation/atan_u8.o
test_objs += validation/atanh_f32.o
test_objs += validation/atanh_u8.o

test_objs += validation/abs_f32.o
test_objs += validation/pow_f32.o
test_objs += validation/mul_f32.o
test_objs += validation/add_f32.o
test_objs += validation/sub_f32.o
test_objs += validation/div_f32.o
test_objs += validation/greater_f32.o
test_objs += validation/less_f32.o
test_objs += validation/less_equal_f32.o
test_objs += validation/logical_and_f32.o
test_objs += validation/logical_or_f32.o
# test_objs += validation/logical_not_f32.o
# test_objs += validation/logical_xor_f32.o
test_objs += validation/log1p_f32.o
test_objs += validation/expm1_f32.o
test_objs += validation/greater_equal_f32.o
test_objs += validation/not_equal_f32.o
test_objs += validation/floor_div_f32.o
test_objs += validation/floor_mod_f32.o
test_objs += validation/elu_f32.o
test_objs += validation/fullyconnected_f32.o
test_objs += validation/relu_f32.o
test_objs += validation/relu6_f32.o
test_objs += validation/rsqrt_f32.o
test_objs += validation/resize_bilinear_f32.o
test_objs += validation/resize_nearestneighbor_f32.o
test_objs += validation/sigmoid_f32.o
test_objs += validation/hard_sigmoid_f32.o
test_objs += validation/softmax_f32.o
test_objs += validation/log_softmax_f32.o
test_objs += validation/sqrt_f32.o
test_objs += validation/select_f32.o
test_objs += validation/leaky_relu_f32.o
test_objs += validation/prelu_f32.o
test_objs += validation/floor_f32.o
test_objs += validation/convolution_f32.o
test_objs += validation/convolution_nchw_f32.o
test_objs += validation/group_convolution_f32.o
test_objs += validation/depthwise_convolution_f32.o
test_objs += validation/convolution3d_f32.o
test_objs += validation/deconvolution3d_f32.o
test_objs += validation/yuv_rgb_scale_f32.o
test_objs += validation/unsorted_segment_max_f32.o
test_objs += validation/unsorted_segment_max_u8.o
test_objs += validation/segment_max_f32.o
test_objs += validation/segment_max_u8.o
test_objs += validation/unsorted_segment_min_f32.o
test_objs += validation/unsorted_segment_min_u8.o
test_objs += validation/segment_min_f32.o
test_objs += validation/segment_min_u8.o
test_objs += validation/unsorted_segment_sum_f32.o
test_objs += validation/unsorted_segment_sum_u8.o
test_objs += validation/segment_sum_f32.o
test_objs += validation/segment_sum_u8.o
test_objs += validation/unsorted_segment_mean_f32.o
test_objs += validation/unsorted_segment_mean_u8.o
test_objs += validation/segment_mean_f32.o
test_objs += validation/segment_mean_u8.o
test_objs += validation/unsorted_segment_prod_f32.o
test_objs += validation/unsorted_segment_prod_u8.o
test_objs += validation/segment_prod_f32.o
test_objs += validation/segment_prod_u8.o
test_objs += validation/threshold_relu_f32.o
test_objs += validation/threshold_relu_u8.o
test_objs += validation/matmul_f32.o
test_objs += validation/matmul_u8.o
test_objs += validation/batch_norm_f32.o
test_objs += validation/batch_norm_u8.o
test_objs += validation/l2_norm_f32.o
test_objs += validation/l2_norm_u8.o

test_objs += validation/cumsum_f32.o
test_objs += validation/cumprod_f32.o
test_objs += validation/reduce_max_f32.o
test_objs += validation/reduce_min_f32.o
test_objs += validation/reduce_sum_f32.o
test_objs += validation/reduce_prod_f32.o
test_objs += validation/reduce_mean_f32.o
test_objs += validation/reduce_logsumexp_f32.o
test_objs += validation/softplus_f32.o
test_objs += validation/softsign_f32.o
test_objs += validation/squeeze_f32.o
test_objs += validation/broadcast_to_f32.o
test_objs += validation/clip_f32.o
test_objs += validation/expand_dims_f32.o
test_objs += validation/reverse_f32.o
test_objs += validation/depth_to_space_f32.o
test_objs += validation/space_to_depth_f32.o
test_objs += validation/tile_f32.o
test_objs += validation/stack_f32.o
test_objs += validation/unstack_f32.o
test_objs += validation/strided_slice_f32.o
test_objs += validation/batch_to_space_f32.o
test_objs += validation/space_to_batch_f32.o
test_objs += validation/gather_f32.o
test_objs += validation/gather_nd_f32.o
test_objs += validation/topk_f32.o
test_objs += validation/topk_u8.o
test_objs += validation/non_max_suppression_f32.o
test_objs += validation/shuffle_channel_f32.o
test_objs += validation/shuffle_channel_u8.o

test_objs += validation/averagepool3d_f32.o
test_objs += validation/maxpool3d_f32.o
test_objs += validation/maxpool_nchw_f32.o
test_objs += validation/averagepool_nchw_f32.o

utils_objs =

utils_objs += utils/math_snr.o
utils_objs += utils/test_utils.o

all: csi

csi: $(utils_objs) $(test_objs)

$(utils_objs): %.o: %.c
	$(CC) -c $(CFLAGS) $(INCLUDE) $< -o $@

$(test_objs): %.o: %.c
	$(CC) -c $(CFLAGS) $(INCLUDE) $< -o $@
	$(CC) $@ $(CFLAGS) $(BOARD) $(utils_objs) -L$(LIB_DIR) -l$(LIB_NAME) -lc -lm -o $@.elf

clean:
	rm -rf  $(test_objs) $(utils_objs) *.a *.asm validation/*.elf validation/*.bin validation/*.asm
