INCLUDE = -I../include -I./utils
CFLAGS += -O2 -g3 -mhard-float -mcpu=c860
CFLAGS += -DCSINN_API=5	# params.api = CSINN_API = CSINN_ANOLE = 5

CC = csky-abiv2-linux-gcc

test_objs =

test_objs += validation_anole/abs.o
test_objs += validation_anole/add.o
#test_objs += validation_anole/argmax.o
#test_objs += validation_anole/argmin.o
test_objs += validation_anole/averagepool.o
test_objs += validation_anole/concat.o
test_objs += validation_anole/convolution_relu.o
test_objs += validation_anole/convolution_relu6.o
test_objs += validation_anole/convolution.o
test_objs += validation_anole/deconvolution.o
test_objs += validation_anole/div.o
test_objs += validation_anole/elu.o
test_objs += validation_anole/equal.o
test_objs += validation_anole/exp.o
test_objs += validation_anole/flatten.o
test_objs += validation_anole/fullyconnected.o
test_objs += validation_anole/global_avgpool.o
test_objs += validation_anole/global_maxpool.o
test_objs += validation_anole/leaky_relu.o
test_objs += validation_anole/lrn.o
test_objs += validation_anole/maximum.o
test_objs += validation_anole/maxpool.o
test_objs += validation_anole/maxpool2d_locat.o
test_objs += validation_anole/minimum.o
test_objs += validation_anole/mean.o
test_objs += validation_anole/mul.o
test_objs += validation_anole/negative.o
test_objs += validation_anole/prelu.o
test_objs += validation_anole/psroipooling.o
test_objs += validation_anole/relu.o
test_objs += validation_anole/relu6.o
test_objs += validation_anole/reshape.o
test_objs += validation_anole/resize.o
test_objs += validation_anole/roipooling.o
test_objs += validation_anole/sigmoid.o
test_objs += validation_anole/softmax.o
test_objs += validation_anole/split.o
test_objs += validation_anole/squeeze.o
test_objs += validation_anole/strided_slice.o
test_objs += validation_anole/sub.o
test_objs += validation_anole/transpose.o
test_objs += validation_anole/unpooling.o


utils_objs =

utils_objs += utils/math_snr.o
utils_objs += utils/test_utils.o

all: csi

csi: $(utils_objs) $(test_objs)

$(utils_objs): %.o: %.c
	$(CC) -c $(CFLAGS) $(INCLUDE) $< -o $@

$(test_objs): %.o: %.c
	$(CC) -c $(CFLAGS) $(INCLUDE) $< -o $@
	$(CC) $@ $(CFLAGS) $(BOARD) $(utils_objs) -L../lib -L../module/acuity-driver/lib/acuity-ovxlib-dev/lib/ \
	-ljpeg -lpng -lz -lcsi_nn2_openvx -Wl,-unresolved-symbols=ignore-in-shared-libs -lm -o $@.elf

clean:
	rm -rf  $(test_objs) $(utils_objs) *.a *.asm validation/*.elf validation/*.bin validation/*.asm
