LIB_DIR = ../../rvv_build
INCLUDE = -I../../include -I../utils -I./layer
CFLAGS = -O0 -g3 -static
CFLAGS += -march=rv64gcv_zfh_xtheadc_xtheadvdot -mabi=lp64d
CFLAGS += -ffunction-sections -fdata-sections -Wl,--gc-sections
CFLAGS += -DCSINN_API=15
LIB_NAME = shl_rvv
CC = riscv64-unknown-linux-gnu-gcc
CPLUS = riscv64-unknown-linux-gnu-g++
TYPE=?

test_objs =

test_objs += add.o
test_objs += averagepool.o
test_objs += concat.o
test_objs += convolution.o
test_objs += group_convolution.o
test_objs += depthwise_convolution.o
test_objs += fullyconnected.o
test_objs += global_avgpool.o
test_objs += global_maxpool.o
test_objs += leaky_relu.o
test_objs += maxpool.o
test_objs += mul.o
test_objs += relu.o
test_objs += sigmoid.o
test_objs += softmax.o
test_objs += sum_stride.o




utils_objs =
utils_objs += ../utils/test_utils.o
# template_objs += ./layer/common.o

all: csi

csi: $(utils_objs) $(test_objs)

$(utils_objs): %.o: %.c
	$(CC) -c $(CFLAGS) $(INCLUDE) $< -o $@

$(test_objs): %.o: %.cpp
	$(CPLUS) -c $(CFLAGS) $(INCLUDE) -D DTYPE=$(TYPE) $< -o $@
	$(CPLUS) $@  $(CFLAGS) $(BOARD) $(utils_objs) $(template_objs) -L$(LIB_DIR) -l$(LIB_NAME) -lc -lm -o $@.elf -lgcov

clean:
	rm -rf  $(test_objs) $(utils_objs) *.a *.asm *.elf *.asm
