CC = csky-abiv2-linux-gcc
INCLUDE = -I../../include -I../utils
CFLAGS += -O2 -g3 -mhard-float -mcpu=c860
CFLAGS += -DCSINN_API=5	# params.api = CSINN_API = CSINN_ANOLE = 5

test_objs =

test_objs += add.o
test_objs += argmax.o
test_objs += avgpool.o
test_objs += batch_normalization.o
test_objs += batch_to_space.o
test_objs += concat.o
test_objs += convolution.o
test_objs += crop.o
test_objs += deconvolution.o
test_objs += depthwise_convolution.o
test_objs += depth_to_space.o
test_objs += div.o
test_objs += fullyconnected.o
test_objs += flatten.o
test_objs += global_avgpool.o
test_objs += global_maxpool.o
test_objs += group_convolution.o
test_objs += l2_normalization.o
test_objs += leaky_relu.o
test_objs += lrn.o
test_objs += maximum.o
test_objs += maxpool.o
test_objs += mean.o
test_objs += minimum.o
test_objs += negative.o
test_objs += pad.o
test_objs += prelu.o
test_objs += relu.o
test_objs += relu1.o
test_objs += relu6.o
test_objs += reshape.o
test_objs += resize.o
test_objs += sigmoid.o
test_objs += softmax.o
test_objs += space_to_batch.o
test_objs += space_to_depth.o
test_objs += split.o
test_objs += squeeze.o
test_objs += strided_slice.o
test_objs += sub.o
test_objs += tanh.o
test_objs += transpose.o


test_objs += ./anole/abs.o
test_objs += ./anole/and.o
test_objs += ./anole/argmin.o
test_objs += ./anole/clip.o
test_objs += ./anole/convolution_relu.o
test_objs += ./anole/convolution_relu6.o
test_objs += ./anole/depthwise_deconvolution.o
test_objs += ./anole/elu.o
test_objs += ./anole/equal.o
test_objs += ./anole/exp.o
test_objs += ./anole/expand_dims.o
test_objs += ./anole/floor.o
test_objs += ./anole/floor_divide.o
test_objs += ./anole/gather.o
test_objs += ./anole/gather_nd.o
test_objs += ./anole/greater.o
test_objs += ./anole/greater_equal.o
test_objs += ./anole/l2_pool.o
test_objs += ./anole/less.o
test_objs += ./anole/less_equal.o
test_objs += ./anole/log.o
test_objs += ./anole/log_softmax.o
test_objs += ./anole/matmul.o
test_objs += ./anole/max.o
test_objs += ./anole/maxpool2d_locat.o
test_objs += ./anole/min.o
test_objs += ./anole/mul.o
test_objs += ./anole/not_equal.o
test_objs += ./anole/or.o
test_objs += ./anole/pow.o
test_objs += ./anole/prod.o
test_objs += ./anole/psroipooling.o
test_objs += ./anole/relun.o
test_objs += ./anole/reorg.o
test_objs += ./anole/reverse.o
test_objs += ./anole/roipooling.o
test_objs += ./anole/rsqrt.o
test_objs += ./anole/select.o
test_objs += ./anole/shuffle_channel.o
test_objs += ./anole/slice.o
test_objs += ./anole/sin.o
test_objs += ./anole/softplus.o
test_objs += ./anole/softrelu.o
test_objs += ./anole/sqrt.o
test_objs += ./anole/square.o
test_objs += ./anole/stack.o
test_objs += ./anole/sum.o
test_objs += ./anole/tile.o
test_objs += ./anole/topk.o
test_objs += ./anole/unpooling.o
test_objs += ./anole/unstack.o


utils_objs =

utils_objs += ../utils/math_snr.o
utils_objs += ../utils/test_utils.o

all: csi

csi: $(utils_objs) $(test_objs)

$(utils_objs): %.o: %.c
	$(CC) -c $(CFLAGS) $(INCLUDE) $< -o $@

$(test_objs): %.o: %.c
	$(CC) -c $(CFLAGS) $(INCLUDE) $< -o $@
	$(CC) $@ $(CFLAGS) $(BOARD) $(utils_objs) -L../../lib -L../../module/acuity-driver/lib/acuity-ovxlib-dev/lib/ \
	-ljpeg -lpng -lz -lcsi_nn2_openvx -Wl,-unresolved-symbols=ignore-in-shared-libs -lm -o $@.elf

clean:
	rm -rf  $(test_objs) $(utils_objs) *.a *.asm *.elf *.bin *.asm
