#!/bin/sh -x

python3 ../../python_ref/add_graph.py
python3 ../../python_ref/averagepool_nchw.py
python3 ../../python_ref/concat.py
python3 ../../python_ref/convolution_nchw.py
python3 ../../python_ref/deconvolution_nchw.py
python3 ../../python_ref/depthwise_convolution_nchw.py
python3 ../../python_ref/depth_to_space.py
python3 ../../python_ref/div.py
python3 ../../python_ref/flatten.py
python3 ../../python_ref/fullyconnected.py
python3 ../../python_ref/global_avgpool_nchw.py
python3 ../../python_ref/global_maxpool_nchw.py
python3 ../../python_ref/group_convolution_nchw.py
python3 ../../python_ref/leaky_relu.py
python3 ../../python_ref/lrn.py
python3 ../../python_ref/maximum.py
python3 ../../python_ref/maxpool_nchw.py
# python3 ../../python_ref/mean_graph.py
python3 ../../python_ref/minimum.py
python3 ../../python_ref/mul.py
python3 ../../python_ref/pad_nchw.py
python3 ../../python_ref/prelu.py
python3 ../../python_ref/relu.py
python3 ../../python_ref/relu1.py
python3 ../../python_ref/relu6.py
python3 ../../python_ref/reshape.py
python3 ../../python_ref/resize_bilinear_nchw.py
python3 ../../python_ref/resize_nearestneighbor.py
python3 ../../python_ref/sigmoid.py
python3 ../../python_ref/space_to_depth.py
python3 ../../python_ref/split_graph.py
python3 ../../python_ref/squeeze.py
python3 ../../python_ref/sub.py
python3 ../../python_ref/tanh.py
python3 ../../python_ref/transpose.py
